version: '3.8'

services:
  # Панель управления (Vite + Express)
  panel:
    build:
      context: ./panel
      dockerfile: Dockerfile
    container_name: timeout-panel
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-change-in-production}
    networks:
      - timeout-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - bot

  # Telegram бот
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: timeout-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - API_BASE_URL=${API_BASE_URL:-http://panel:3000/api}
      - API_SECRET_KEY=${API_SECRET_KEY:-secret_key_12345}
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - timeout-network
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep node || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  timeout-network:
    driver: bridge
    name: timeout-network

